#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 2:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=eg_toric_3d
nodes=4
iters=33600
shared=/scratch-shared/tmp.zp8w9ZGXKp

let iter=$iters/$nodes

mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/threshold_batchsql.py $i 24 eg toric $iter -l 32 36 -p 0.02733 0.02767 0.02833 0.02867 0.02933 0.02967 -sql $name -of $shared/$name -me -db
)&
done
wait
