#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 4:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=eg_planar_2d
nodes=4
iters=52800
shared=/scratch-shared/tmp.zp8w9ZGXKp

let iter=$iters/$nodes
mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/threshold_batchsql.py $i 24 eg planar $iter -l 8 16 24 32 40 48 56 64 72 -p 0.0965 0.0975 0.0985 0.0995 0.1005 -sql $name -of $shared/$name -db
)&
done
wait
