#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 24:00:00

module load 2019
module load Python/3.7.5-foss-2018b

i=$1
iter=$2
name=$3
shared=$4

folder=$TMPDIR

cd $folder
git clone https://github.com/watermarkhu/OpenSurfaceSim

cd OpenSurfaceSim
git checkout batch

cd simulator/decoder/blossom5
make

cd ../../..
# pyenv local 3.7.4
python run_threshold_sqlbatch.py $i 24 mwpm toric $iter8 13 18 23 28 33 -p 0.005 0.006 0.007 0.008 0.009 0.01 0.011 0.012 0.013 0.014 0.015 0.016 0.017 0.018 0.019 0.02 -of $shared/$name -me -db
