#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 24:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=ufbb_toric_3d_lowerror
nodes=8
iters=192000
shared=/scratch-shared/tmp.l5jNGplBBW

let iter=$iters/$nodes
mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/run_threshold_sqlbatch.py $i 24 ufbb toric $iter -l 8 13 18 23 28 33 -p 0.005 0.006 0.007 0.008 0.009 0.01 0.011 0.012 0.013 0.014 0.015 0.016 0.017 0.018 0.019 0.02 -of $shared/$name -me -db
)&
done
wait
