#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 24:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=uf_planar_3d
nodes=4
iters=96000
shared=/scratch-shared/tmp.zp8w9ZGXKp

let iter=$iters/$nodes
mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/threshold_batchsql.py $i 24 uf planar $iter -l 8 12 16 20 24 28 32 36 40 -p 0.025 0.02533 0.02567 0.026 0.02633 0.02667 0.027 0.02733 0.02767 0.028 0.02833 0.02867 0.029 -sql $name -of $shared/$name -me -db
)&
done
wait
