#!/bin/bash
#SBATCH -N 4 -t 12:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=ufbb_planar_3d_extra
nodes=4
iters=11520
shared=/scratch-shared/tmp.4MrYmgXnYZ

let iter=$iters/$nodes
mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/run_threshold_sqlbatch.py $i 24 ufbb planar $iter -l 40 44 -p 0.025 0.02533 0.02567 0.026 0.02633 0.02667 0.027 0.02733 0.02767 0.028 -of $shared/$name -db -me
)&
done
wait
