#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 24:00:00

module load 2019
module load Python/3.7.5-foss-2018b

nodes=4
iters=33600

let iter=$iters/$nodes

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 bash $HOME/scripts/mwpm_planar_2d_b $i $iter
)&
done
wait
