#!/bin/bash
#SBATCH --constraint=haswell -N 4 -t 24:00:00

module load 2019
module load Python/3.7.5-foss-2018b

name=ufuwg_planar_3d
nodes=4
iters=96000
shared=/scratch-shared/tmp.4MrYmgXnYZ

let iter=$iters/$nodes
mkdir -p $shared/$name

for (( i=0; i<$nodes; i++)); do
(
srun -N 1 python $HOME/oop_surface_code/run_threshold_sqlbatch.py $i 24 uf_uwg planar $iter -l 8 12 16 20 24 28 32 36 -p 0.025 0.0255 0.026 0.0265 0.027 0.0275 0.028 0.0285 0.029 -of $shared/$name -me -db
)&
done
wait
